#!/usr/bin/env python3
"""Generate .ai/skills/CATALOG.md from each skill's SKILL.md frontmatter.

The catalog is a tool-agnostic index: one row per skill with a one-sentence
summary and the situation that should make an agent pull it in. It is the
single source for "what skills exist and when to read them" — every mod repo
vendors it verbatim via `make sync`, and each AGENTS.md just points here
instead of carrying its own (drift-prone) copy of the table.

Source of truth is the `description:` field, which by convention reads
"<summary>. TRIGGER <when...>". Run from the concord repo root:

    python3 scripts/gen-skills-catalog.py        # write CATALOG.md
    python3 scripts/gen-skills-catalog.py --check # exit 1 if it would change
"""

from __future__ import annotations

import pathlib
import sys

SKILLS_DIR = pathlib.Path(".ai/skills")
CATALOG = SKILLS_DIR / "CATALOG.md"

HEADER = """\
<!-- GENERATED by scripts/gen-skills-catalog.py from each SKILL.md frontmatter. Do not edit by hand; run `make catalog`. -->
# Concord domain skills

The `mc-*` skills under `.ai/skills/` are the suite's shared Minecraft/Fabric
domain knowledge. They are edited in the [concord repo](https://github.com/rfizzle/concord)
and vendored into every member repo via `make sync` — this catalog rides
along, so it is always in step with the skills actually present.

**How each agent consumes them:** Claude Code auto-loads skills via the
`.claude/skills` symlink. Google Jules, OpenCode, and any other tool should read
the relevant `SKILL.md` directly **before** working in its subject area — use the
"Pull it in when…" column to decide which.

| Skill | What it does | Pull it in when… |
|---|---|---|
"""


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal single-line-value YAML frontmatter parser (no deps)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t")):
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()
    return fields


def split_description(desc: str) -> tuple[str, str]:
    """Return (summary, trigger). Splits on the first 'TRIGGER' token."""
    idx = desc.find("TRIGGER")
    if idx == -1:
        return desc.strip().rstrip("."), ""
    summary = desc[:idx].strip().rstrip(" .")
    trigger = desc[idx + len("TRIGGER"):].strip()
    # Lead-in word lost with TRIGGER; reattach a natural one.
    trigger = trigger.lstrip(" :")
    return summary, trigger


def render() -> str:
    rows = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        fm = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = fm.get("name", skill_md.parent.name)
        summary, trigger = split_description(fm.get("description", ""))
        link = f"[`{name}`]({name}/SKILL.md)"
        rows.append(f"| {link} | {summary} | {trigger} |")
    return HEADER + "\n".join(rows) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    content = render()
    if check:
        current = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
        if current != content:
            print(
                "CATALOG.md is stale — run `make catalog` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("CATALOG.md is up to date.")
        return 0
    CATALOG.write_text(content, encoding="utf-8")
    print(f"wrote {CATALOG} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
